### ISSUE TITLE
BUG: When turning off right click, this causes a bug in combat mode

### ISSUE THREAD

**Issue by djsmithdev** [djsmithdev/combatmode#21]
When turning off "right click" under "base clicks," right-clicking while Combat Mode is active turns off Combat Mode and must be manually turned back on using the assigned keybind. Right-clicking again does not do anything. Left-clicking while Combat Mode is active makes the player move forward (presumably because holding both right & left-click makes the player move as well)

**Comment by djsmithdev** [comment]
if you disable the base clicks overriding AND have Free Look locked in:
when right-clicking, it unlocks the cursor. Subsequent right-clicks do nothing
when left-clicking the player moves forward

**Comment by sampconrad** [comment]
More of a feature request than a bug. One that I'm not too keen on adding. The mod is made with the assumption that you'll override the base keybinds at the very least. I don't wanna deal with the ramifications of using Free Look and at the same time trying to preserve the base left and right click functionalities.

**Comment by sampconrad** [comment]
Solved with #28
